//------------------------------------------------------------------------------
// <auto-generated>
//     Codice generato da un modello.
//
//     Le modifiche manuali a questo file potrebbero causare un comportamento imprevisto dell'applicazione.
//     Se il codice viene rigenerato, le modifiche manuali al file verranno sovrascritte.
// </auto-generated>
//------------------------------------------------------------------------------

namespace EntityModel
{
    using System;
    using System.Data.Entity;
    using System.Data.Entity.Infrastructure;
    
    public partial class RetailHubEntities : DbContext
    {
        public RetailHubEntities()
            : base("name=RetailHubEntities")
        {
        }
    
        protected override void OnModelCreating(DbModelBuilder modelBuilder)
        {
            throw new UnintentionalCodeFirstException();
        }
    
        public virtual DbSet<tabGruppoAttributi> tabGruppoAttributi { get; set; }
        public virtual DbSet<tabListini> tabListini { get; set; }
        public virtual DbSet<tabPrezzoProdottoDiListino> tabPrezzoProdottoDiListino { get; set; }
        public virtual DbSet<tabProdotti> tabProdotti { get; set; }
        public virtual DbSet<tabProdottiDiListino> tabProdottiDiListino { get; set; }
        public virtual DbSet<tabProdottiToGruppoAttributi> tabProdottiToGruppoAttributi { get; set; }
        public virtual DbSet<tabSetAttributiProdottoListino> tabSetAttributiProdottoListino { get; set; }
        public virtual DbSet<TabOpzioniPostazione> TabOpzioniPostazione { get; set; }
    }
}
