//------------------------------------------------------------------------------
// <auto-generated>
//     Codice generato da un modello.
//
//     Le modifiche manuali a questo file potrebbero causare un comportamento imprevisto dell'applicazione.
//     Se il codice viene rigenerato, le modifiche manuali al file verranno sovrascritte.
// </auto-generated>
//------------------------------------------------------------------------------

namespace EntityModel
{
    using System;
    using System.Collections.Generic;
    
    public partial class tabListini
    {
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2214:DoNotCallOverridableMethodsInConstructors")]
        public tabListini()
        {
            this.tabPrezzoProdottoDiListino = new HashSet<tabPrezzoProdottoDiListino>();
        }
    
        public System.Guid ID { get; set; }
        public Nullable<System.DateTime> CreationDate { get; set; }
        public System.DateTime LastModifiedDate { get; set; }
        public string LastModifiedBy { get; set; }
        public string Nome { get; set; }
        public Nullable<System.DateTime> DataInizioValidita { get; set; }
        public Nullable<System.DateTime> DataFineValidita { get; set; }
        public int TipoListino { get; set; }
    
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<tabPrezzoProdottoDiListino> tabPrezzoProdottoDiListino { get; set; }
    }
}
