//------------------------------------------------------------------------------
// <auto-generated>
//     Codice generato da un modello.
//
//     Le modifiche manuali a questo file potrebbero causare un comportamento imprevisto dell'applicazione.
//     Se il codice viene rigenerato, le modifiche manuali al file verranno sovrascritte.
// </auto-generated>
//------------------------------------------------------------------------------

namespace EntityModel
{
    using System;
    using System.Collections.Generic;
    
    public partial class tabPrezzoProdottoDiListino
    {
        public System.Guid IDListino { get; set; }
        public System.Guid IDProdottoDiListino { get; set; }
        public Nullable<decimal> Prezzo { get; set; }
        public Nullable<decimal> Maggiorazione { get; set; }
        public bool isPredefinito { get; set; }
    
        public virtual tabListini tabListini { get; set; }
        public virtual tabProdottiDiListino tabProdottiDiListino { get; set; }
    }
}
