//------------------------------------------------------------------------------
// <auto-generated>
//     Codice generato da un modello.
//
//     Le modifiche manuali a questo file potrebbero causare un comportamento imprevisto dell'applicazione.
//     Se il codice viene rigenerato, le modifiche manuali al file verranno sovrascritte.
// </auto-generated>
//------------------------------------------------------------------------------

namespace EntityModel
{
    using System;
    using System.Collections.Generic;
    
    public partial class tabProdottiToGruppoAttributi
    {
        public System.Guid ID { get; set; }
        public Nullable<System.DateTime> CreationDate { get; set; }
        public System.DateTime LastModifiedDate { get; set; }
        public string LastModifiedBy { get; set; }
        public System.Guid IDProdotto { get; set; }
        public System.Guid IDGruppoAttributi { get; set; }
        public string Valore { get; set; }
    
        public virtual tabGruppoAttributi tabGruppoAttributi { get; set; }
        public virtual tabProdotti tabProdotti { get; set; }
    }
}
