//------------------------------------------------------------------------------
// <auto-generated>
//     Codice generato da un modello.
//
//     Le modifiche manuali a questo file potrebbero causare un comportamento imprevisto dell'applicazione.
//     Se il codice viene rigenerato, le modifiche manuali al file verranno sovrascritte.
// </auto-generated>
//------------------------------------------------------------------------------

namespace EntityModel
{
    using System;
    using System.Collections.Generic;
    
    public partial class tabProdottiDiListino
    {
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2214:DoNotCallOverridableMethodsInConstructors")]
        public tabProdottiDiListino()
        {
            this.tabPrezzoProdottoDiListino = new HashSet<tabPrezzoProdottoDiListino>();
            this.tabSetAttributiProdottoListino = new HashSet<tabSetAttributiProdottoListino>();
        }
    
        public System.Guid Id { get; set; }
        public string SKU { get; set; }
        public System.Guid IDProdotto { get; set; }
    
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<tabPrezzoProdottoDiListino> tabPrezzoProdottoDiListino { get; set; }
        public virtual tabProdotti tabProdotti { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<tabSetAttributiProdottoListino> tabSetAttributiProdottoListino { get; set; }
    }
}
